include:
  - component: gitlab.com/maxem/devops/ci-components/container@main
    inputs:
      repository: tools/chronicle
      image_tag: "${IMAGE_TAG}"

container:build:
  before_script:
    - >
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        export IMAGE_TAG="$CI_COMMIT_TAG"
      else
        export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
      fi
